name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variable
        run: |
          echo "VERSION_NAME=1.0.0" >> $GITHUB_ENV

      - name: Show Environment Variable
        run: |
          echo "Version Name: $VERSION_NAME"
